import React, { useState, useRef, useEffect } from 'react';
import { 
  Music, 
  Layers, 
  Wand2, 
  Download, 
  Play, 
  Settings, 
  FileAudio, 
  CheckCircle2, 
  AlertCircle,
  Cpu,
  Mic2,
  Piano,
  Activity,
  Terminal
} from 'lucide-react';

const LogicAutomationHub = () => {
  const [file, setFile] = useState(null);
  const [processing, setProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [logs, setLogs] = useState([]);
  const [generatedScript, setGeneratedScript] = useState('');
  const [activeTab, setActiveTab] = useState('config'); // 'config' | 'script' | 'simulation'
  
  // Configuration State
  const [config, setConfig] = useState({
    detectTempo: true,
    detectKey: true,
    applyStemSplitter: true,
    convertToMidi: true,
    createProject: true,
    saveLocation: "~/Music/Logic/Automated/",
    midiThreshold: 50
  });

  const fileInputRef = useRef(null);

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      generateScript(e.target.files[0], config);
    }
  };

  const toggleConfig = (key) => {
    const newConfig = { ...config, [key]: !config[key] };
    setConfig(newConfig);
    if (file) generateScript(file, newConfig);
  };

  const addLog = (message, type = 'info') => {
    setLogs(prev => [...prev, { time: new Date().toLocaleTimeString(), message, type }]);
  };

  // This function generates the AppleScript based on user settings
  const generateScript = (currentFile, currentConfig) => {
    const filePath = currentFile ? `"${currentFile.name}"` : '"your_audio_file.wav"';
    const fullPathPlaceholder = currentFile ? `POSIX path of (choose file with prompt "Select ${currentFile.name} to confirm path")` : 'choose file';

    let script = `-- Logic Pro Automation Script
-- Generated by Logic Automation Hub
-- Usage: Open Script Editor on macOS, paste this code, and run.

tell application "Logic Pro"
    activate
end tell

tell application "System Events"
    tell process "Logic Pro"
        
        -- 1. Create New Project
        ${currentConfig.createProject ? `
        try
            click menu item "New..." of menu "File" of menu bar 1
            delay 1
            -- Handle "New Project" dialog if it appears (simplified)
            keystroke return
        on error
            -- Project might already be open
        end try` : '-- Skipping Project Creation'}
        
        delay 2

        -- 2. Import Audio File
        -- We use a placeholder for the path because browsers can't see real full paths
        set audioFile to ${fullPathPlaceholder}
        
        tell application "Logic Pro"
            import audioFile
        end tell
        
        delay 2
        
        -- 3. Select the new Track
        -- Logic usually selects the last imported track automatically
        
        ${currentConfig.detectTempo ? `
        -- 4. Detect Tempo (Smart Tempo)
        try
            click menu item "Smart Tempo Editor" of menu "Window" of menu bar 1
            delay 1
            -- Simulate "Analyze" click (Context dependent, robust fallback)
            keystroke "analyze" 
        end try` : '-- Skipping Tempo Detection'}
        
        ${currentConfig.applyStemSplitter ? `
        -- 5. Apply Stem Splitter (Logic Pro 11+)
        -- Note: This requires the track region to be selected
        try
            -- Use GUI Scripting to find Stem Splitter in contextual menu or Functions
            click menu item "Stem Splitter..." of menu "Functions" of menu "Window" of menu bar 1
            
            delay 1
            -- Confirm Split in Dialog
            keystroke return
            
            -- Wait for processing (Simulation of wait loop)
            delay 5 
        on error
            display notification "Ensure Logic Pro 11 is installed for Stem Splitter"
        end try` : '-- Skipping Stem Splitter'}

        ${currentConfig.convertToMidi ? `
        -- 6. Convert to MIDI
        -- Often labeled as "Create MIDI Track from Audio" or Flex Pitch
        delay 1
        try
             keystroke "e" using {control down, option down} -- Example shortcut for export/convert
             -- Or use menu:
             -- click menu item "Create MIDI Track from Audio Region" of menu "Track" of menu bar 1
        end try` : '-- Skipping MIDI Conversion'}
        
    end tell
end tell

display notification "Automation Complete" with title "Logic Pro Hub"
`;
    setGeneratedScript(script);
  };

  const runSimulation = () => {
    if (!file) return;
    setActiveTab('simulation');
    setProcessing(true);
    setProgress(0);
    setLogs([]);

    const steps = [
      { msg: "Initializing CoreAudio bridge...", duration: 1000 },
      { msg: "Connecting to Logic Pro via AppleScript...", duration: 1500 },
      { msg: `Importing "${file.name}" into Timeline...`, duration: 1200 },
      config.detectTempo && { msg: "Analyzing transients for Smart Tempo...", duration: 2000 },
      config.detectKey && { msg: "Detecting Key Signature... (Result: Am)", duration: 1500 },
      config.applyStemSplitter && { msg: "Invoking Neural Engine for Stem Separation...", duration: 3500 },
      config.applyStemSplitter && { msg: "Separating: Vocals, Drums, Bass, Other...", duration: 2000 },
      config.convertToMidi && { msg: "Converting Audio Transients to MIDI data...", duration: 2500 },
      { msg: "Finalizing Project Structure...", duration: 1000 },
      { msg: "Done.", duration: 500 }
    ].filter(Boolean);

    let currentStep = 0;

    const executeStep = () => {
      if (currentStep >= steps.length) {
        setProcessing(false);
        setProgress(100);
        return;
      }

      const step = steps[currentStep];
      addLog(step.msg, 'process');
      
      // Calculate progress based on step count
      setProgress(Math.round(((currentStep + 1) / steps.length) * 100));
      
      currentStep++;
      setTimeout(executeStep, step.duration);
    };

    executeStep();
  };

  const copyToClipboard = () => {
    const textArea = document.createElement("textarea");
    textArea.value = generatedScript;
    document.body.appendChild(textArea);
    textArea.select();
    document.execCommand('copy');
    document.body.removeChild(textArea);
    addLog("Script copied to clipboard", "success");
  };

  return (
    <div className="flex flex-col h-screen bg-slate-900 text-slate-300 font-sans overflow-hidden">
      {/* Header */}
      <header className="bg-slate-950 border-b border-slate-800 p-4 flex items-center justify-between shadow-md">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 bg-orange-600 rounded-lg flex items-center justify-center shadow-[0_0_15px_rgba(234,88,12,0.3)]">
            <Activity className="text-white w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-slate-100 tracking-tight">Logic Pro Automation Hub</h1>
            <p className="text-xs text-slate-500">Workflow Generator & Bridge</p>
          </div>
        </div>
        <div className="flex items-center space-x-4 text-sm">
          <div className="flex items-center space-x-2 text-green-500 bg-green-500/10 px-3 py-1 rounded-full border border-green-500/20">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <span>System Ready</span>
          </div>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        {/* Left Sidebar: Configuration */}
        <div className="w-80 bg-slate-900 border-r border-slate-800 flex flex-col overflow-y-auto z-10">
          <div className="p-6 space-y-8">
            
            {/* File Upload Section */}
            <div className="space-y-3">
              <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Source Audio</label>
              <div 
                onClick={() => fileInputRef.current.click()}
                className={`border-2 border-dashed rounded-xl p-6 text-center cursor-pointer transition-all duration-300 group
                  ${file ? 'border-orange-500/50 bg-orange-500/5' : 'border-slate-700 hover:border-slate-500 hover:bg-slate-800'}`}
              >
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileChange} 
                  className="hidden" 
                  accept="audio/*" 
                />
                {file ? (
                  <div className="space-y-2">
                    <FileAudio className="w-10 h-10 text-orange-500 mx-auto" />
                    <p className="text-sm font-medium text-slate-200 truncate px-2">{file.name}</p>
                    <p className="text-xs text-slate-500">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <Music className="w-10 h-10 text-slate-600 mx-auto group-hover:text-slate-400 transition-colors" />
                    <p className="text-sm text-slate-400">Drop audio file here</p>
                  </div>
                )}
              </div>
            </div>

            {/* Automation Actions */}
            <div className="space-y-4">
              <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Automation Steps</label>
              
              <div className="space-y-2">
                <Toggle 
                  label="Detect Tempo (Smart Tempo)" 
                  active={config.detectTempo} 
                  onClick={() => toggleConfig('detectTempo')} 
                  icon={<Activity className="w-4 h-4" />}
                />
                <Toggle 
                  label="Detect Key Signature" 
                  active={config.detectKey} 
                  onClick={() => toggleConfig('detectKey')} 
                  icon={<Music className="w-4 h-4" />}
                />
                <Toggle 
                  label="Apply Stem Splitter" 
                  active={config.applyStemSplitter} 
                  onClick={() => toggleConfig('applyStemSplitter')} 
                  icon={<Layers className="w-4 h-4" />}
                />
                <Toggle 
                  label="Convert to MIDI" 
                  active={config.convertToMidi} 
                  onClick={() => toggleConfig('convertToMidi')} 
                  icon={<Piano className="w-4 h-4" />}
                />
              </div>
            </div>

             <button 
                onClick={runSimulation}
                disabled={!file || processing}
                className={`w-full py-3 px-4 rounded-lg font-medium flex items-center justify-center space-x-2 transition-all
                  ${!file 
                    ? 'bg-slate-800 text-slate-600 cursor-not-allowed' 
                    : processing 
                      ? 'bg-orange-600/80 text-white cursor-wait' 
                      : 'bg-orange-600 hover:bg-orange-500 text-white shadow-lg shadow-orange-600/20'}`}
              >
                {processing ? <Wand2 className="w-5 h-5 animate-spin" /> : <Play className="w-5 h-5 fill-current" />}
                <span>{processing ? 'Processing...' : 'Simulate Workflow'}</span>
              </button>

          </div>
        </div>

        {/* Main Content Area */}
        <div className="flex-1 flex flex-col bg-slate-950 relative">
          
          {/* Tabs */}
          <div className="flex border-b border-slate-800 bg-slate-900/50 backdrop-blur-sm">
             <TabButton 
               active={activeTab === 'config'} 
               onClick={() => setActiveTab('config')}
               label="Workflow Overview"
               icon={<Settings className="w-4 h-4" />}
             />
             <TabButton 
               active={activeTab === 'script'} 
               onClick={() => setActiveTab('script')}
               label="Generated AppleScript"
               icon={<Terminal className="w-4 h-4" />}
             />
             <TabButton 
               active={activeTab === 'simulation'} 
               onClick={() => setActiveTab('simulation')}
               label="Live Console"
               icon={<Cpu className="w-4 h-4" />}
             />
          </div>

          {/* Content Views */}
          <div className="flex-1 overflow-y-auto p-8">
            
            {activeTab === 'config' && (
              <div className="max-w-4xl mx-auto space-y-8">
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Visualizer Card */}
                    <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col items-center justify-center min-h-[300px] relative overflow-hidden">
                       <div className="absolute inset-0 bg-gradient-to-br from-slate-900 to-slate-950"></div>
                       <div className="relative z-10 text-center space-y-4">
                          {file ? (
                            <>
                              <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-orange-500 to-pink-600 flex items-center justify-center shadow-2xl">
                                <Mic2 className="w-10 h-10 text-white" />
                              </div>
                              <div>
                                <h3 className="text-lg font-medium text-white">{file.name}</h3>
                                <p className="text-slate-500">Ready for Logic Pro Import</p>
                              </div>
                              <div className="flex items-center justify-center space-x-2 pt-4">
                                 {config.applyStemSplitter && <Badge text="Stem Split" color="bg-blue-500/20 text-blue-400" />}
                                 {config.convertToMidi && <Badge text="Audio to MIDI" color="bg-purple-500/20 text-purple-400" />}
                              </div>
                            </>
                          ) : (
                            <div className="text-slate-600 flex flex-col items-center">
                              <Layers className="w-16 h-16 mb-4 opacity-50" />
                              <p>No active project</p>
                            </div>
                          )}
                       </div>
                    </div>

                    {/* Info Panel */}
                    <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                      <h3 className="text-lg font-medium text-white mb-4 flex items-center gap-2">
                        <AlertCircle className="w-5 h-5 text-blue-400" />
                        Browser Limitation
                      </h3>
                      <p className="text-slate-400 text-sm leading-relaxed mb-6">
                        Web browsers cannot directly control desktop software like Logic Pro due to security sandboxing. 
                        This app acts as a <strong>Control Center</strong>.
                      </p>
                      <div className="space-y-4">
                        <div className="flex items-start gap-3">
                          <div className="w-6 h-6 rounded-full bg-slate-800 flex items-center justify-center text-xs font-bold text-slate-400 shrink-0">1</div>
                          <p className="text-sm text-slate-400">Configure your import settings on the left.</p>
                        </div>
                        <div className="flex items-start gap-3">
                          <div className="w-6 h-6 rounded-full bg-slate-800 flex items-center justify-center text-xs font-bold text-slate-400 shrink-0">2</div>
                          <p className="text-sm text-slate-400">Go to the <strong>Generated AppleScript</strong> tab.</p>
                        </div>
                        <div className="flex items-start gap-3">
                          <div className="w-6 h-6 rounded-full bg-slate-800 flex items-center justify-center text-xs font-bold text-slate-400 shrink-0">3</div>
                          <p className="text-sm text-slate-400">Download/Copy the script and run it on your Mac to execute the workflow automatically.</p>
                        </div>
                      </div>
                    </div>
                 </div>
              </div>
            )}

            {activeTab === 'script' && (
              <div className="h-full flex flex-col">
                 <div className="flex items-center justify-between mb-4">
                   <h2 className="text-lg font-medium text-white">AppleScript Automation</h2>
                   <button 
                    onClick={copyToClipboard}
                    className="flex items-center space-x-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-md text-sm transition-colors"
                   >
                     <Download className="w-4 h-4" />
                     <span>Copy Script</span>
                   </button>
                 </div>
                 <div className="flex-1 relative group">
                    <div className="absolute inset-0 bg-slate-900 rounded-xl border border-slate-800 p-4 overflow-auto font-mono text-sm text-green-400 shadow-inner custom-scrollbar">
                      <pre>{generatedScript || "-- Configure settings and upload a file to generate script"}</pre>
                    </div>
                 </div>
              </div>
            )}

            {activeTab === 'simulation' && (
              <div className="max-w-3xl mx-auto">
                {/* Progress Section */}
                <div className="mb-8 bg-slate-900 rounded-xl border border-slate-800 p-8">
                   <div className="flex items-center justify-between mb-4">
                     <h3 className="text-white font-medium">Automation Status</h3>
                     <span className="text-orange-500 font-mono">{progress}%</span>
                   </div>
                   <div className="h-2 bg-slate-800 rounded-full overflow-hidden">
                     <div 
                      className="h-full bg-gradient-to-r from-orange-600 to-yellow-500 transition-all duration-300 ease-out"
                      style={{ width: `${progress}%` }}
                     ></div>
                   </div>
                </div>

                {/* Console Logs */}
                <div className="space-y-2 font-mono text-sm">
                   {logs.map((log, idx) => (
                     <div key={idx} className="flex items-start gap-3 animate-in fade-in slide-in-from-bottom-2 duration-300">
                       <span className="text-slate-600 shrink-0">[{log.time}]</span>
                       <span className={`${
                         log.type === 'success' ? 'text-green-400' : 
                         log.type === 'error' ? 'text-red-400' : 
                         'text-slate-300'
                       }`}>
                         {log.type === 'process' && <span className="text-orange-500 mr-2">{'>'}</span>}
                         {log.message}
                       </span>
                     </div>
                   ))}
                   {logs.length === 0 && (
                     <div className="text-center text-slate-600 py-12">
                       Waiting to start simulation...
                     </div>
                   )}
                </div>
              </div>
            )}

          </div>
        </div>
      </div>
    </div>
  );
};

// Sub-components for cleaner code

const Toggle = ({ label, active, onClick, icon }) => (
  <div 
    onClick={onClick}
    className={`flex items-center justify-between p-3 rounded-lg cursor-pointer border transition-all duration-200
      ${active 
        ? 'bg-slate-800 border-orange-500/50 shadow-[0_0_10px_rgba(249,115,22,0.1)]' 
        : 'bg-slate-900/50 border-slate-800 hover:border-slate-700'}`}
  >
    <div className="flex items-center space-x-3">
      <div className={`p-1.5 rounded-md transition-colors ${active ? 'bg-orange-500 text-white' : 'bg-slate-800 text-slate-500'}`}>
        {icon}
      </div>
      <span className={`text-sm font-medium ${active ? 'text-slate-200' : 'text-slate-500'}`}>{label}</span>
    </div>
    <div className={`w-10 h-5 rounded-full relative transition-colors ${active ? 'bg-orange-600' : 'bg-slate-700'}`}>
      <div className={`absolute top-1 w-3 h-3 bg-white rounded-full transition-all duration-200 ${active ? 'left-6' : 'left-1'}`}></div>
    </div>
  </div>
);

const TabButton = ({ active, onClick, label, icon }) => (
  <button 
    onClick={onClick}
    className={`flex items-center space-x-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors
      ${active 
        ? 'border-orange-500 text-white bg-slate-800/50' 
        : 'border-transparent text-slate-500 hover:text-slate-300 hover:bg-slate-800/30'}`}
  >
    {icon}
    <span>{label}</span>
  </button>
);

const Badge = ({ text, color }) => (
  <span className={`px-2.5 py-0.5 rounded text-xs font-medium border border-white/5 ${color}`}>
    {text}
  </span>
);

export default LogicAutomationHub;