"""Validation suite for the quaternion beam-search tool."""

import random
from quaternions import (Quat, ONE, GEN, INV, lps_factor, word_str)
from tree import PrimeTree
from stallings import subgroup_index


def reduce_word(w):
    out = []
    for c in w:
        if out and out[-1] == INV[c]:
            out.pop()
        else:
            out.append(c)
    return out


def test_lps_roundtrip(trials=3000):
    random.seed(1)
    for _ in range(trials):
        L = random.randint(1, 10)
        w = []
        for _ in range(L):
            w.append(random.choice([i for i in range(6)
                                    if not (w and i == INV[w[-1]])]))
        q = ONE
        for i in w:
            q = q * GEN[i]
        unit, word = lps_factor(q.primitive())
        assert word == w, f"roundtrip failed: {word_str(w)} -> {word_str(word)}"
        assert unit == ONE, f"unexpected unit {unit}"
    print(f"[ok] LPS factorisation round-trips on {trials} reduced words")


def test_homomorphism(trials=1000):
    random.seed(2)
    for _ in range(trials):
        wa = [random.randrange(6) for _ in range(random.randint(0, 6))]
        wb = [random.randrange(6) for _ in range(random.randint(0, 6))]
        qa = ONE
        for i in wa:
            qa = qa * GEN[i]
        qb = ONE
        for i in wb:
            qb = qb * GEN[i]
        _, wpa = lps_factor(qa.primitive())
        _, wpb = lps_factor(qb.primitive())
        _, wprod = lps_factor((qa * qb).primitive())
        assert wprod == reduce_word(list(wpa) + list(wpb))
    print(f"[ok] q -> LPS word is a homomorphism F_3 (checked {trials} products)")


def test_tree_action():
    T13 = PrimeTree(13, 60)
    a = Quat(1, 2, 0, 0)
    b, bi = Quat(3, 0, 2, 0), Quat(3, 0, -2, 0)
    v0 = T13.vertex(ONE)
    assert T13.vertex(a.primitive()) == v0, "a should fix v0 in T13"
    assert T13.vertex(b.primitive()) != v0, "b should move v0 in T13"
    assert T13.vertex((b * bi).primitive()) == v0
    # a^12 fixes the whole radius-1 ball: b a^12 b^-1 in PH(Z[1/5])
    a12 = ONE
    for _ in range(12):
        a12 = a12 * a
    h = (b * a12 * bi).primitive()
    n = int(h.norm())
    while n % 5 == 0:
        n //= 5
    assert n == 1, "b a^12 b^-1 should have norm a power of 5"
    print("[ok] T13 action: a fixes v0, b moves it, b a^12 b^-1 in PH(Z[1/5])")


def test_stallings():
    assert subgroup_index([[0], [2], [4]])[0] == 1          # <x,y,z> = F_3
    assert subgroup_index([[0]])[1]["rank"] == 1            # <x> rank 1
    assert subgroup_index([[0, 2, 1, 3]])[1]["rank"] == 1   # <[x,y]> rank 1
    assert subgroup_index([[0, 0], [2], [4]])[0] is None    # infinite index
    # index-2 subgroup: kernel of x,y,z |-> 1 in Z/2 is generated by even words
    even = [[0, 0], [2, 2], [4, 4], [0, 2], [0, 4], [2, 4],
            [0, 3], [0, 5], [2, 5]]
    assert subgroup_index(even)[0] == 2
    print("[ok] Stallings folding correct on known subgroups")


if __name__ == "__main__":
    test_lps_roundtrip()
    test_homomorphism()
    test_tree_action()
    test_stallings()
    print("\nAll tests passed.")
